-- Gupta Traders compatibility migration for the existing production schema.
-- Additive only: no tables or rows are dropped or deleted.
create extension if not exists pgcrypto;

-- Preserve UUID-backed roles and profiles.role_id. Seed only missing standard roles.
insert into public.roles (name, description)
select v.name, v.description from (values ('Manager','ERP manager'),('Cashier','POS cashier')) v(name,description)
where not exists (select 1 from public.roles r where lower(r.name)=lower(v.name));

alter table public.categories add column if not exists slug text, add column if not exists icon text, add column if not exists color text, add column if not exists image_url text, add column if not exists status text default 'active', add column if not exists sort_order integer default 0, add column if not exists deleted_at timestamptz, add column if not exists deleted_by uuid references public.profiles(id), add column if not exists updated_at timestamptz default now();
update public.categories set slug=coalesce(nullif(slug,''), regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g')) where slug is null;

alter table public.products add column if not exists hindi_name text, add column if not exists brand text, add column if not exists pack_size text, add column if not exists loose_unit text, add column if not exists loose_conversion_factor numeric, add column if not exists hsn_code text, add column if not exists description text, add column if not exists status text default 'active', add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists created_by uuid references public.profiles(id), add column if not exists deleted_at timestamptz, add column if not exists deleted_by uuid references public.profiles(id);
alter table public.inventory add column if not exists updated_at timestamptz default now();
alter table public.stock_movements add column if not exists reason text, add column if not exists created_by uuid references public.profiles(id);

alter table public.customers add column if not exists customer_code text, add column if not exists city text, add column if not exists state text, add column if not exists postal_code text, add column if not exists gstin text, add column if not exists customer_type text default 'retail', add column if not exists status text default 'active', add column if not exists balance numeric, add column if not exists profile_image_url text, add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists deleted_at timestamptz, add column if not exists deleted_by uuid references public.profiles(id);
update public.customers set balance=coalesce(opening_balance,0) where balance is null;
alter table public.customers alter column balance set default 0;
alter table public.suppliers add column if not exists supplier_code text, add column if not exists contact_person text, add column if not exists alternate_phone text, add column if not exists city text, add column if not exists state text, add column if not exists postal_code text, add column if not exists gstin text, add column if not exists pan text, add column if not exists bank_name text, add column if not exists bank_account text, add column if not exists ifsc text, add column if not exists status text default 'active', add column if not exists balance numeric, add column if not exists credit_limit numeric default 0, add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists deleted_at timestamptz, add column if not exists deleted_by uuid references public.profiles(id);
update public.suppliers set balance=coalesce(opening_balance,0) where balance is null;
alter table public.suppliers alter column balance set default 0;

alter table public.sales add column if not exists sold_by uuid references public.profiles(id), add column if not exists tax_amount numeric default 0, add column if not exists cgst numeric default 0, add column if not exists sgst numeric default 0, add column if not exists payment_reference text, add column if not exists status text default 'completed', add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists updated_at timestamptz default now();
update public.sales set tax_amount=coalesce(tax_amount,tax,0) where tax_amount is null;
alter table public.sale_items add column if not exists product_name text, add column if not exists sku text, add column if not exists unit text, add column if not exists unit_price numeric, add column if not exists unit_cost numeric default 0, add column if not exists tax_rate numeric default 0, add column if not exists tax_amount numeric default 0, add column if not exists line_total numeric, add column if not exists metadata jsonb default '{}'::jsonb;
update public.sale_items set unit_price=coalesce(unit_price,selling_price), line_total=coalesce(line_total,total), product_name=coalesce(product_name,'') where unit_price is null or line_total is null or product_name is null;

alter table public.purchases add column if not exists purchased_by uuid references public.profiles(id), add column if not exists supplier_invoice_number text, add column if not exists tax_amount numeric default 0, add column if not exists cgst numeric default 0, add column if not exists sgst numeric default 0, add column if not exists payment_method text, add column if not exists payment_reference text, add column if not exists status text default 'completed', add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists updated_at timestamptz default now();
update public.purchases set tax_amount=coalesce(tax_amount,tax,0) where tax_amount is null;
alter table public.purchase_items add column if not exists product_name text, add column if not exists sku text, add column if not exists unit text, add column if not exists unit_price numeric, add column if not exists tax_rate numeric default 0, add column if not exists tax_amount numeric default 0, add column if not exists line_total numeric, add column if not exists metadata jsonb default '{}'::jsonb;
update public.purchase_items set unit_price=coalesce(unit_price,purchase_price), line_total=coalesce(line_total,total), product_name=coalesce(product_name,product,'') where unit_price is null or line_total is null or product_name is null;

alter table public.sales_returns add column if not exists return_number text, add column if not exists processed_by uuid references public.profiles(id), add column if not exists subtotal numeric default 0, add column if not exists tax_amount numeric default 0, add column if not exists refund_method text, add column if not exists notes text;
alter table public.sale_return_items add column if not exists sale_item_id uuid references public.sale_items(id), add column if not exists unit_price numeric, add column if not exists tax_rate numeric default 0, add column if not exists tax_amount numeric default 0, add column if not exists line_total numeric;
update public.sale_return_items set unit_price=coalesce(unit_price,price), line_total=coalesce(line_total,total) where unit_price is null or line_total is null;
alter table public.purchase_returns add column if not exists return_number text, add column if not exists processed_by uuid references public.profiles(id), add column if not exists subtotal numeric default 0, add column if not exists tax_amount numeric default 0, add column if not exists refund_method text;
alter table public.purchase_return_items add column if not exists purchase_item_id uuid references public.purchase_items(id), add column if not exists unit_price numeric, add column if not exists tax_rate numeric default 0, add column if not exists tax_amount numeric default 0, add column if not exists line_total numeric;
update public.purchase_return_items set unit_price=coalesce(unit_price,price), line_total=coalesce(line_total,total) where unit_price is null or line_total is null;

alter table public.held_bills add column if not exists held_by uuid references public.profiles(id), add column if not exists label text, add column if not exists totals jsonb default '{}'::jsonb, add column if not exists held_at timestamptz default now(), add column if not exists updated_at timestamptz default now();
update public.held_bills set held_by=coalesce(held_by,created_by), held_at=coalesce(held_at,created_at) where held_by is null or held_at is null;
alter table public.expenses add column if not exists expense_type text default 'miscellaneous', add column if not exists category text, add column if not exists payee text, add column if not exists bill_number text, add column if not exists payment_reference text, add column if not exists metadata jsonb default '{}'::jsonb, add column if not exists updated_at timestamptz default now();
alter table public.settings add column if not exists printer_config jsonb default '{}'::jsonb;
create index if not exists products_deleted_idx on public.products(deleted_at);
create index if not exists categories_deleted_idx on public.categories(deleted_at);
create index if not exists customers_deleted_idx on public.customers(deleted_at);
create index if not exists suppliers_deleted_idx on public.suppliers(deleted_at);

create or replace function public.set_updated_at() returns trigger language plpgsql as $$begin new.updated_at=now(); return new; end$$;
create or replace function public.record_document_payment() returns trigger language plpgsql security definer set search_path=public as $$begin if coalesce(new.paid_amount,0)>0 then if tg_table_name='sales' then insert into public.payments(sale_id,payment_type,payment_method,amount,reference_number,notes) values(new.id,'sale',coalesce(new.payment_method,'Cash'),new.paid_amount,new.payment_reference,'POS payment'); elsif tg_table_name='purchases' then insert into public.payments(purchase_id,payment_type,payment_method,amount,reference_number,notes) values(new.id,'purchase',coalesce(new.payment_method,'Cash'),new.paid_amount,new.payment_reference,'Purchase payment'); end if; end if; return new; end$$;
do $$ declare t text; begin foreach t in array array['profiles','categories','products','customers','suppliers','sales','purchases','expenses','held_bills','settings'] loop if exists(select 1 from information_schema.columns where table_schema='public' and table_name=t and column_name='updated_at') and not exists(select 1 from pg_trigger where tgrelid=format('public.%I',t)::regclass and tgname='set_updated_at') then execute format('create trigger set_updated_at before update on public.%I for each row execute function public.set_updated_at()',t); end if; end loop; end $$;
do $$ begin if not exists(select 1 from pg_trigger where tgrelid='public.sales'::regclass and tgname='record_sale_payment') then create trigger record_sale_payment after insert on public.sales for each row execute function public.record_document_payment(); end if; if not exists(select 1 from pg_trigger where tgrelid='public.purchases'::regclass and tgname='record_purchase_payment') then create trigger record_purchase_payment after insert on public.purchases for each row execute function public.record_document_payment(); end if; end $$;

create or replace function public.current_role_name() returns text language sql stable security definer set search_path=public as $$select lower(r.name) from public.profiles p join public.roles r on r.id=p.role_id where p.id=auth.uid() and p.is_active limit 1$$;
create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select auth.uid() is not null and public.current_role_name() is not null$$;
create or replace function public.is_manager() returns boolean language sql stable security definer set search_path=public as $$select public.current_role_name() in ('admin','manager')$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select public.current_role_name()='admin'$$;

create sequence if not exists public.sale_invoice_seq;
create sequence if not exists public.purchase_number_seq;

create or replace function public.change_stock(p_product_id uuid,p_delta numeric,p_type text,p_reason text default null,p_reference_type text default null,p_reference_id uuid default null) returns numeric language plpgsql security definer set search_path=public as $$declare v_quantity numeric; v_after numeric; begin if not public.is_manager() then raise exception 'Insufficient permission'; end if; if p_delta=0 then raise exception 'Stock delta cannot be zero'; end if; insert into public.inventory(product_id,quantity,available_quantity) values(p_product_id,0,0) on conflict(product_id) do nothing; select quantity into v_quantity from public.inventory where product_id=p_product_id for update; v_after:=v_quantity+p_delta; if v_after<0 then raise exception 'Insufficient stock'; end if; update public.inventory set quantity=v_after,available_quantity=greatest(0,v_after-coalesce(reserved_quantity,0)),updated_at=now() where product_id=p_product_id; insert into public.stock_movements(product_id,movement_type,quantity,reference_type,reference_id,notes,created_by) values(p_product_id,p_type,p_delta,p_reference_type,p_reference_id,p_reason,auth.uid()); return v_after; end$$;

create or replace function public.complete_sale(p_sale jsonb,p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare v_id uuid:=gen_random_uuid(); v_no text; v jsonb; p public.products%rowtype; stock numeric; total numeric:=0; tax_total numeric:=0; qty numeric; price numeric; disc numeric; begin if not public.is_staff() then raise exception 'Authentication required'; end if; v_no:=coalesce(nullif(p_sale->>'invoice_number',''),'INV-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(nextval('sale_invoice_seq')::text,6,'0')); insert into public.sales(id,customer_id,invoice_number,sale_date,subtotal,discount,tax,total_amount,paid_amount,due_amount,payment_status,payment_method,payment_reference,notes,sold_by,status) values(v_id,nullif(p_sale->>'customer_id','')::uuid,v_no,coalesce((p_sale->>'sale_date')::timestamptz,now()),0,coalesce((p_sale->>'discount')::numeric,0),0,0,coalesce((p_sale->>'paid_amount')::numeric,0),0,coalesce(p_sale->>'payment_status','paid'),p_sale->>'payment_method',p_sale->>'payment_reference',p_sale->>'notes',auth.uid(),'completed'); for v in select * from jsonb_array_elements(p_items) loop select * into p from public.products where id=(v->>'product_id')::uuid and is_active and coalesce(status,'active')='active' and deleted_at is null for share; if not found then raise exception 'Product not found or inactive'; end if; qty:=(v->>'quantity')::numeric; price:=coalesce((v->>'unit_price')::numeric,(v->>'selling_price')::numeric,p.selling_price); disc:=coalesce((v->>'discount')::numeric,0); if qty<=0 then raise exception 'Invalid sale quantity'; end if; select quantity into stock from public.inventory where product_id=p.id for update; if coalesce(stock,0)<qty then raise exception 'Insufficient stock for %',p.name; end if; insert into public.sale_items(sale_id,product_id,selling_price,discount,tax,total,product_name,sku,unit,unit_price,tax_rate,tax_amount,line_total) values(v_id,p.id,price,disc,coalesce((v->>'tax')::numeric,0),round(qty*price-disc,2),p.name,p.sku,p.unit,price,p.gst_rate,round(qty*price*p.gst_rate/100,2),round(qty*price-disc,2)); total:=total+qty*price-disc; tax_total:=tax_total+qty*price*p.gst_rate/100; update public.inventory set quantity=quantity-qty,available_quantity=greatest(0,quantity-qty-coalesce(reserved_quantity,0)),updated_at=now() where product_id=p.id; insert into public.stock_movements(product_id,movement_type,quantity,reference_type,reference_id,notes,created_by) values(p.id,'sale',-qty,'sale',v_id,'POS sale',auth.uid()); end loop; update public.sales set subtotal=round(total,2),tax=round(tax_total,2),tax_amount=round(tax_total,2),total_amount=round(total+tax_total-coalesce((p_sale->>'discount')::numeric,0),2),due_amount=greatest(0,round(total+tax_total-coalesce((p_sale->>'discount')::numeric,0),2)-coalesce((p_sale->>'paid_amount')::numeric,0)) where id=v_id; return jsonb_build_object('id',v_id,'invoice_number',v_no); end$$;

create or replace function public.complete_purchase(p_purchase jsonb,p_items jsonb) returns jsonb language plpgsql security definer set search_path=public as $$declare v_id uuid:=gen_random_uuid(); v_no text; v jsonb; p public.products%rowtype; total numeric:=0; tax_total numeric:=0; qty numeric; price numeric; begin if not public.is_manager() then raise exception 'Insufficient permission'; end if; v_no:=coalesce(nullif(p_purchase->>'invoice_number',''),'PUR-'||to_char(current_date,'YYYYMMDD')||'-'||lpad(nextval('purchase_number_seq')::text,6,'0')); insert into public.purchases(id,supplier_id,invoice_number,purchase_date,subtotal,discount,tax,total_amount,paid_amount,due_amount,payment_status,payment_method,payment_reference,notes,purchased_by,status) values(v_id,nullif(p_purchase->>'supplier_id','')::uuid,v_no,coalesce((p_purchase->>'purchase_date')::timestamptz,now()),0,coalesce((p_purchase->>'discount')::numeric,0),0,0,coalesce((p_purchase->>'paid_amount')::numeric,0),0,coalesce(p_purchase->>'payment_status','unpaid'),p_purchase->>'payment_method',p_purchase->>'payment_reference',p_purchase->>'notes',auth.uid(),'completed'); for v in select * from jsonb_array_elements(p_items) loop select * into p from public.products where id=(v->>'product_id')::uuid for share; if not found then raise exception 'Product not found'; end if; qty:=(v->>'quantity')::numeric; price:=coalesce((v->>'unit_price')::numeric,(v->>'purchase_price')::numeric,p.purchase_price); if qty<=0 then raise exception 'Invalid purchase quantity'; end if; insert into public.purchase_items(purchase_id,product_id,quantity,purchase_price,discount,tax,total,product_name,sku,unit,unit_price,tax_rate,tax_amount,line_total) values(v_id,p.id,qty,price,coalesce((v->>'discount')::numeric,0),coalesce((v->>'tax')::numeric,0),round(qty*price,2),p.name,p.sku,p.unit,price,p.gst_rate,round(qty*price*p.gst_rate/100,2),round(qty*price,2)); total:=total+qty*price; tax_total:=tax_total+qty*price*p.gst_rate/100; insert into public.inventory(product_id,quantity,available_quantity) values(p.id,qty,qty) on conflict(product_id) do update set quantity=inventory.quantity+excluded.quantity,available_quantity=inventory.available_quantity+excluded.quantity,updated_at=now(); insert into public.stock_movements(product_id,movement_type,quantity,reference_type,reference_id,notes,created_by) values(p.id,'purchase',qty,'purchase',v_id,'Purchase receipt',auth.uid()); end loop; update public.purchases set subtotal=round(total,2),tax=round(tax_total,2),tax_amount=round(tax_total,2),total_amount=round(total+tax_total-coalesce((p_purchase->>'discount')::numeric,0),2),due_amount=greatest(0,round(total+tax_total-coalesce((p_purchase->>'discount')::numeric,0),2)-coalesce((p_purchase->>'paid_amount')::numeric,0)) where id=v_id; return jsonb_build_object('id',v_id,'invoice_number',v_no); end$$;

grant execute on function public.current_role_name(),public.is_staff(),public.is_manager(),public.is_admin(),public.change_stock(uuid,numeric,text,text,text,uuid),public.complete_sale(jsonb,jsonb),public.complete_purchase(jsonb,jsonb) to authenticated;
